### ISSUE TITLE
Critical Error when filling chests with Repurpose installed.

### ISSUE THREAD

**Issue by BrisingrAerowing** [Brian-Wuest/MC-Prefab#138]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 28.2.4
    1. Mod Version: 1.4.0.13

[This line](https://github.com/Brian-Wuest/MC-Prefab/blob/MC-1.14.4/src/main/java/com/wuest/prefab/Structures/Predefined/StructureAlternateStart.java#L194) has uppercase characters in the resource location, which causes a crash as they are considered invalid. This also seems to have broken my world, though that may be unrelated.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.4.0.14 and uploaded to CurseForge and is waiting for approval.

**Comment by Brian-Wuest** [comment]
This has been also fixed with 1.5.0.4 which was just uploaded to CurseForge. 

Closing issue.

**Comment by BrisingrAerowing** [comment]
You only fixed this for the Starter House. The Moderate house still crashes.

**Comment by Brian-Wuest** [comment]
Razelfrazen...no idea why I made the code separate. 

Thank you for that and sorry.

**Comment by Brian-Wuest** [comment]
Not sure why this was closed....

**Comment by Brian-Wuest** [comment]
This has been released with 1.4.0.15 and 1.5.0.5 and approved on curseforge. Closing issue.
